services:

  db:
    container_name: restausimplon-db
    image: postgres:17.5-alpine3.22
    ports:
      - "${LOCAL_PORT}:${POSTGRES_PORT}"
   
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - restausimplon-data:/var/lib/postgresql/data



volumes:
  restausimplon-data:
  


    