"""roles_et_permissions

Revision ID: 062e3799489e
Revises: c9199c99d18d
Create Date: 2025-08-07 15:52:33.112865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '062e3799489e'
down_revision: Union[str, Sequence[str], None] = 'c9199c99d18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name="pk_role"),
    sa.UniqueConstraint('role', name="unique_role")
    )
    op.create_table('permission',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name="fk_role"),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], name="fk_user"),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name="pk_permission")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    op.drop_table('role')
    # ### end Alembic commands ###
