"""ajout_salt_dans_user_info

Revision ID: a008f61cbdff
Revises: 062e3799489e
Create Date: 2025-08-08 10:44:25.449716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a008f61cbdff"
down_revision: Union[str, Sequence[str], None] = "062e3799489e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_detail", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_order_detail_order_id", "order", ["order_id"], ["id"]
        )

    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.drop_column("salt")

    with op.batch_alter_table("order_detail", schema=None) as batch_op:
        batch_op.drop_constraint("fk_order_detail_order_id", type_="foreignkey")

    # ### end Alembic commands ###
