"""ajout_de_la_table_menu_item

Revision ID: 0b560f49bda5
Revises: 0c8d58b6e75e
Create Date: 2025-08-06 15:02:56.896803

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b560f49bda5"
down_revision: Union[str, Sequence[str], None] = "0c8d58b6e75e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "category",
            sa.Enum("starter", "main_course", "dessert", name="menucategory"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="menu_item_pk"),
    )
    with op.batch_alter_table("menu_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_menu_item_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("menu_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_menu_item_name"))

    op.drop_table("menu_item")
    # ### end Alembic commands ###
