"""contraintes_user_info

Revision ID: c9199c99d18d
Revises: 62c7cfbcd4c4
Create Date: 2025-08-07 13:35:37.833634

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9199c99d18d"
down_revision: Union[str, Sequence[str], None] = "62c7cfbcd4c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_info_email"))
        batch_op.create_index(batch_op.f("ix_user_info_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_info_email"))
        batch_op.create_index(batch_op.f("ix_user_info_email"), ["email"], unique=False)
    # ### end Alembic commands ###
