"""ajout_modele_detail_commande

Revision ID: 62c7cfbcd4c4
Revises: fa9ac7c3e0e8
Create Date: 2025-08-06 16:50:57.977328

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62c7cfbcd4c4'
down_revision: Union[str, Sequence[str], None] = 'fa9ac7c3e0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_detail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_item.id'], name='fk_order_detail_menu'), ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='fk_order_detail_order'),
    sa.PrimaryKeyConstraint('id', name="pk_order_detail"),
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    # ### end Alembic commands ###
