name: mypy lint

on: push

jobs:
  mypy:
    runs-on: python:slim-3.12
    steps:
      - name: checkout
        uses: action/checkout@v5

      - name: installing requirements
        run: pip install -r ./requirements.txt

      - name: linting with mypy
        run: mypy .