name: mypy lint

on: push

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: action/checkout@v5

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: installing mypy 
        run: pip install --no-cache-dir -r mypy

      - name: linting with mypy
        run: mypy .