name: mypy lint

on: push

jobs:
  mypy:
    runs-on: python:slim-3.12
    steps:
      - name: checkout
        uses: action/checkout@v5

      - name: installing mypy
        run: pip install --no-cache-dir -r mypy

      - name: linting with mypy
        run: mypy .