name: Tests d'intégration

on:
  pull_request:
    branches:
      - dev

jobs:
  #######
  setup:
    name: Set up de l'environnement
    runs-on: ubuntu-24.04
    env:
      JWT_SECRET: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      LOCAL_API_PORT: 8000
      ADMIN_EMAIL: "admin@restau-simplon.com"
      ADMIN_PASSWORD: "admin"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      LOCAL_DB_PORT: 5432
      API_URL: http://restausimplon-api:8000
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5

      - name: Lancement des tests à travers docker compose
        run: docker compose -f compose.test.yaml --profile test up --build -d

      - name: ee
        run: docker build -f integration.Dockerfile -t tests .

      - name: eea
        run: docker run --network restau_simplon_restausimplon-network tests

      - name: Nettoyage des conteneurs
        if: always()
        run: docker compose -f compose.test.yaml down
